version: '3'


services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    container_name: prueba_celsia_db
    volumes:
      - ./postgres:/var/lib/postgresql/data